/* GROUP BY : 저자별 카테고리별 매출액 집계하기 (GROUP 기준 여러개) */
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_PRICE
FROM AUTHOR AS A 
    RIGHT JOIN BOOK AS B 
        ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
          FROM BOOK_SALES
          WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
          GROUP BY BOOK_ID) AS S
        ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;